version: "3.7"

services:
  dev-backend:
    build: ./dev/backend
    working_dir: /backend
    container_name: dev-backend
    command: python3 dev-entry.py
    volumes:
      - ./dev/backend/:/backend
    depends_on:
      - unknown_mongo
    env_file:
      - ./dev/.env
  dev-frontend:
    build: ./dev/frontend
    container_name: dev-frontend
    working_dir: /frontend
    command: pnpm docker-dev
    volumes:
      - ./dev/frontend/.svelte-kit/:/frontend/.svelte-kit/
      - ./dev/frontend/patches/:/frontend/patches/
      - ./dev/frontend/scripts/:/frontend/scripts/
      - ./dev/frontend/src/:/frontend/src/
      - ./dev/frontend/static/:/frontend/static/
      - ./dev/frontend/package.json:/frontend/package.json
      - ./dev/frontend/postcss.config.js:/frontend/postcss.config.js
      - ./dev/frontend/svelte.config.js:/frontend/svelte.config.js
      - ./dev/frontend/tailwind.config.js:/frontend/tailwind.config.js
      - ./dev/frontend/vite.config.ts:/frontend/vite.config.ts
    env_file:
      - ./dev/.env
    environment:
      - isDocker=true
  unknown_mongo:
    image: mongo
    container_name: unknown_mongo
    restart: unless-stopped
    env_file:
      - ./dev/.env
    volumes:
      - "./dev/data:/data/db"
  dev-client:
    image: nginx
    ports:
      - 2080:80
    volumes:
      - type: bind
        source: ./dev/dev-proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    depends_on:
      - dev-frontend
      - dev-backend

  mock-interview-saver:
    build: .
    container_name: mock-interview-saver
    command: python /app/start.py
    restart: always
    ports:
      - 3000:5000
    env_file:
      - ./mock-interview-saver/.env
    volumes:
      - ./mock-interview-saver/root/:/app/root/
      - ./mock-interview-saver/start.py:/app/start.py
      - ./mock-interview-saver/store/:/app/store/      
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    depends_on:
      - mock-interview-saver

